"""Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from fitbit_web_api.api.activity_api import ActivityApi


class TestActivityApi(unittest.IsolatedAsyncioTestCase):
    """ActivityApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ActivityApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_activities_log(self) -> None:
        """Test case for add_activities_log

        Log Activity
        """

    async def test_add_favorite_activities(self) -> None:
        """Test case for add_favorite_activities

        Add Favorite Activity
        """

    async def test_add_update_activities_goals(self) -> None:
        """Test case for add_update_activities_goals

        Update Activity Goals
        """

    async def test_delete_activities_log(self) -> None:
        """Test case for delete_activities_log

        Delete Activity Log
        """

    async def test_delete_favorite_activities(self) -> None:
        """Test case for delete_favorite_activities

        Delete Favorite Activity
        """

    async def test_get_activities_by_date(self) -> None:
        """Test case for get_activities_by_date

        Get Activity Summary by Date
        """

    async def test_get_activities_goals(self) -> None:
        """Test case for get_activities_goals

        Get Activity Goals
        """

    async def test_get_activities_log(self) -> None:
        """Test case for get_activities_log

        Get Lifetime Stats
        """

    async def test_get_activities_log_list(self) -> None:
        """Test case for get_activities_log_list

        Get Activity Log List
        """

    async def test_get_activities_tcx(self) -> None:
        """Test case for get_activities_tcx

        Get Activity TCX
        """

    async def test_get_activities_type_detail(self) -> None:
        """Test case for get_activities_type_detail

        Get Activity Type
        """

    async def test_get_activities_types(self) -> None:
        """Test case for get_activities_types

        Browse Activity Types
        """

    async def test_get_favorite_activities(self) -> None:
        """Test case for get_favorite_activities

        Get Favorite Activities
        """

    async def test_get_frequent_activities(self) -> None:
        """Test case for get_frequent_activities

        Get Frequent Activities
        """

    async def test_get_recent_activities(self) -> None:
        """Test case for get_recent_activities

        Get Recent Activity Types
        """


if __name__ == "__main__":
    unittest.main()
