"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.  # noqa: E501

OpenAPI spec version: 1

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

from swagger_client.api.breathing_rate_api import BreathingRateApi


class TestBreathingRateApi(unittest.TestCase):
    """BreathingRateApi unit test stubs"""

    def setUp(self):
        self.api = BreathingRateApi()

    def tearDown(self):
        pass

    def test_get_breathing_rate_summary_by_date(self):
        """
        Test case for get_breathing_rate_summary_by_date

        Get Breathing Rate Summary by Date  # noqa: E501
        """
        pass

    def test_get_breathing_rate_summary_by_interval(self):
        """
        Test case for get_breathing_rate_summary_by_interval

        Get Breathing Rate Summary by Interval  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
