"""
Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from fitbit_web_api.api.breathing_rate_api import BreathingRateApi


class TestBreathingRateApi(unittest.IsolatedAsyncioTestCase):
    """BreathingRateApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = BreathingRateApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_breathing_rate_summary_by_date(self) -> None:
        """
        Test case for get_breathing_rate_summary_by_date

        Get Breathing Rate Summary by Date
        """
        pass

    async def test_get_breathing_rate_summary_by_interval(self) -> None:
        """
        Test case for get_breathing_rate_summary_by_interval

        Get Breathing Rate Summary by Interval
        """
        pass


if __name__ == "__main__":
    unittest.main()
