# Changes here will be overwritten by Copier
_commit: f1153eb
_src_path: https://github.com/browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2023'
documentation: false
email: simone.chemelli@gmail.com
full_name: Simone Chemelli
github_username: chemelli74
has_cli: false
initial_commit: true
open_source_license: Apache Software License 2.0
package_name: fitbit_web_api
project_name: fitbit-web-api
project_short_description: Fitbit Web API
project_slug: fitbit-web-api
run_poetry_install: true
setup_github: false
setup_pre_commit: true

