{
  "openapi": "3.0.1",
  "info": {
    "title": "Fitbit Web API Explorer",
    "description": "Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authori[...]",
    "termsOfService": "https://dev.fitbit.com/legal/platform-terms-of-service/",
    "contact": {
      "name": "Web API Support",
      "url": "https://dev.fitbit.com/build/reference/web-api/help/"
    },
    "version": "1"
  },
  "servers": [
    {
      "url": "https://api.fitbit.com/"
    }
  ],
  "tags": [
    {
      "name": "Active Zone Minutes Intraday Time Series",
      "description": "The Active Zone Minutes (AZM) Intraday Time Series endpoints retrieve the user's heart-pumping activity for a specific date or 24 hour period. Intraday support can extend the detail-level response to include 1min, 5min and 15min for Active Zone Minutes."
    },
    {
      "name": "Active Zone Minutes Time Series",
      "description": "The Active Zone Minutes (AZM) Time Series endpoints are used for querying the user's heart-pumping activity throughout the day. "
    },
    {
      "name": "Activity",
      "description": "The Activity endpoints are used to query and/or modify a Fitbit user's daily activity data. "
    },
    {
      "name": "Activity Intraday Time Series",
      "description": "The Activity Intraday Time Series endpoints retrieve the data for a given resource on a specific date or 24 hour period.  Intraday support can extend the detail-level response to include 1min, 5min and 15min for the activity."
    },
    {
      "name": "Activity Time Series",
      "description": "The Activity Time Series endpoints are used to query a Fitbit user's activity data over a period of time, either by specifying a date and time period, or a date range."
    },
    {
      "name": "Authorization",
      "description": "The Authorization endpoints allow an application to onboard Fitbit users who want to share their data with the specified application. The application can initiate the consent flow for new users, obtain the access token and refresh tokens, validate the tokens, and revoke consent to the user."
    },
    {
      "name": "Body",
      "description": "The Body endpoints are used for querying and modifying the user's body fat and weight data."
    },
    {
      "name": "Body Time Series",
      "description": "The Body Time Series endpoints are used for querying body fat and weight data over a period of time either by specifying a date and time period, or a date range."
    },
    {
      "name": "Breathing Rate",
      "description": "Breathing Rate or Respiratory Rate is a measurement of your average breaths per minute at night."
    },
    {
      "name": "Breathing Rate Intraday",
      "description": "The Breathing Rate Intraday endpoint returns the  average breathing rate throughout the day and categories your breathing rate by sleep stage."
    },
    {
      "name": "Cardio Fitness Score (VO2 Max)",
      "description": "The Cardio Fitness Score (also known as VO2 Max) endpoints are used for querying the maximum or optimum rate at which the user’s heart, lungs, and muscles can effectively use oxygen during exercise."
    },
    {
      "name": "Devices",
      "description": "The Devices endpoints displays information about the devices paired to a user's account."
    },
    {
      "name": "Electrocardiogram",
      "description": "The Electrocardiogram (also known as ECG) endpoint is used for querying the user's on-device ECG readings."
    },
    {
      "name": "Friends",
      "description": "The Friends endpoints display information about the specified user's friends and the friend's leaderboard."
    },
    {
      "name": "Heart Rate Intraday Time Series",
      "description": "The Heart Rate Intraday Time Series retrieves the heart rate data on a specific date or 24 hour period. Intraday support can extend the detail-level response to include 1sec, 1min, 5min or 15min for Heart Rate."
    },
    {
      "name": "Heart Rate Time Series",
      "description": "The Heart Rate Time Series endpoints are used for querying the user's heart rate data."
    },
    {
      "name": "Heart Rate Variability",
      "description": "The Heart Rate Variability (HRV) endpoints are used for querying the user’s heart rate variability data."
    },
    {
      "name": "Heart Rate Variability Intraday",
      "description": "The Heart Rate Variability Intraday endpoint returns the HRV rate at various times and returns Root Mean Square of Successive Differences (rmssd), Low Frequency (LF), High Frequency (HF), and Coverage data for a given measurement."
    },
    {
      "name": "Irregular Rhythm Notifications",
      "description": "The Irregular Rhythm Notifications (also known as IRN) endpoints are used for querying the user's engagement with the IRN feature and the alerts received. The IRN API is for research use or investigational use only, and is not intended for clinical or diagnostic purposes."
    },
    {
      "name": "Nutrition",
      "description": "The Nutrition endpoints are used for querying and modifying the food and water data."
    },
    {
      "name": "Nutrition Time Series",
      "description": "The Nutrition Time Series endpoints are used for querying food- and water-related data over a period of time either by specifying a date and time period, or a date range."
    },
    {
      "name": "Sleep",
      "description": "The Sleep endpoints are used for querying and modifying the user’s general sleep data."
    },
    {
      "name": "SpO2",
      "description": "SpO2 (Oxygen Saturation) is a measurement of your blood oxygen level. "
    },
    {
      "name": "SpO2 Intraday",
      "description": "The SpO2 Intraday endpoints return the SpO2 values calculated on a 5-minute exponentially-moving average."
    },
    {
      "name": "Subscriptions",
      "description": "The Subscription endpoints allow an application to request notifications to user's specific data collection."
    },
    {
      "name": "Temperature",
      "description": "The Temperature endpoints are used for querying either the core temperature data logged manually by the user, or the skin temperature recorded by the device while the user is asleep."
    },
    {
      "name": "User",
      "description": "The User endpoints display information about the user's profile information, the regional locale & language settings, and their badges collected"
    }
  ],
  "paths": {
    "/oauth2/token": {
      "post": {
        "tags": ["Authorization"],
        "summary": "Get OAuth 2 access token",
        "description": "Retrieves an OAuth 2 access token.",
        "operationId": "oauthToken"
      }
    },
    "/1.1/oauth2/introspect": {
      "post": {
        "tags": ["Authorization"],
        "summary": "Retrieve the active state of an OAuth 2.0 token",
        "description": "Retrieves the active state of an OAuth 2.0 token. It follows https://tools.ietf.org/html/rfc7662.",
        "operationId": "introspect",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/oauth2/revoke": {
      "post": {
        "tags": ["Authorization"],
        "summary": "Revokes consent of the access token or refresh token",
        "description": "Revokes consent of the access token or refresh token",
        "operationId": "revoke",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}.json": {
      "get": {
        "tags": ["Active Zone Minutes Intraday Time Series"],
        "summary": "Get AZM Intraday by Date",
        "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.",
        "operationId": "getAZMByDateIntraday",
        "security": [
          {
            "oauth2": ["activity"]
          }
        ]
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "tags": ["Active Zone Minutes Intraday Time Series"],
        "summary": "Get AZM Intraday by Date",
        "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.",
        "operationId": "getAZMByDateTimeSeriesIntraday",
        "security": [
          {
            "oauth2": ["activity"]
          }
        ]
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/{detail-level}.json": {
      "get": {
        "tags": ["Active Zone Minutes Intraday Time Series"],
        "summary": "Get AZM Intraday by Interval",
        "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.",
        "operationId": "getAZMByIntervalIntraday",
        "security": [
          {
            "oauth2": ["activity"]
          }
        ]
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/time/{start-time}/{end-time}.json": {
      "get": {
        "tags": ["Active Zone Minutes Intraday Time Series"],
        "summary": "Get AZM Intraday by Interval",
        "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.",
        "operationId": "getAZMByIntervalTimeSeriesIntraday",
        "security": [
          {
            "oauth2": ["activity"]
          }
        ]
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{date}/{period}.json": {
      "get": {
        "tags": ["Active Zone Minutes Time Series"],
        "summary": "Get AZM Time Series by Date",
        "description": "Returns the daily summary values over a period of time by specifying a date and time period.",
        "operationId": "getAZMTimeSeriesByDate",
        "security": [
          {
            "oauth2": ["activity"]
          }
        ]
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}.json": {
      "get": {
        "tags": ["Active Zone Minutes Time Series"],
        "summary": "Get AZM Time Series by Interval",
        "description": "Returns the daily summary values over an interval by specifying a date range.",
        "operationId": "getAZMTimeSeriesByInterval",
        "security": [
          {
            "oauth2": ["activity"]
          }
        ]
      }
    },
    "/1/user/-/activities/date/{date}.json": {
      "get": {
        "tags": ["Activity"],
        "summary": "Get Activity Summary by Date ",
        "description": "Retrieves a summary and list of a user's activities and activity log entries for a given day.",
        "operationId": "getActivitiesByDate",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/{resource-path}/date/{base-date}/{end-date}.json": {
      "get": {
        "tags": ["Activity Time Series"],
        "summary": "Get Activity Resource by Date Range",
        "description": "Returns activities time series data in the specified range for a given resource.",
        "operationId": "getActivitiesResourceByDateRange",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/tracker/{resource-path}/date/{base-date}/{end-date}.json": {
      "get": {
        "tags": ["Activity Time Series"],
        "summary": "Get Activity Tracker Resource by Date Range Time Series",
        "description": "Returns time series data in the specified range for a given resource.",
        "operationId": "getActivitiesTrackerResourceByDateRange",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/{resource-path}/date/{date}/{period}.json": {
      "get": {
        "tags": ["Activity Time Series"],
        "summary": "Get Activity Time Series",
        "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesResourceByDatePeriod",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/tracker/{resource-path}/date/{date}/{period}.json": {
      "get": {
        "tags": ["Activity Time Series"],
        "summary": "Get Activity Time Series",
        "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesTrackerResourceByDatePeriod",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/{resource-path}/date/{base-date}/{end-date}/{detail-level}.json": {
      "get": {
        "tags": ["Activity Intraday Time Series"],
        "summary": "Get Activity Intraday Time Series",
        "description": "Returns the Activity Intraday Time Series for a given resource in the format requested.",
        "operationId": "getActivitiesResourceByDateRangeIntraday",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json": {
      "get": {
        "tags": ["Activity Intraday Time Series"],
        "summary": "Get Intraday Time Series",
        "description": "Returns the Intraday Time Series for a given resource in the format requested.",
        "operationId": "getActivitiesResourceByDateIntraday",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/{resource-path}/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "tags": ["Activity Intraday Time Series"],
        "summary": "Get Activity Intraday Time Series",
        "description": "Returns the Intraday Time Series for a given resource in the format requested.",
        "operationId": "getActivitiesResourceByDateRangeTimeSeriesIntraday",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "tags": ["Activity Intraday Time Series"],
        "summary": "Get Intraday Time Series",
        "description": "Returns the Intraday Time Series for a given resource in the format requested.",
        "operationId": "getActivitiesResourceByDateTimeSeriesIntraday",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities.json": {
      "get": {
        "tags": ["Activity"],
        "summary": "Get Lifetime Stats",
        "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesLog",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      },
      "post": {
        "tags": ["Activity"],
        "summary": "Log Activity",
        "description": "The Log Activity endpoint creates log entry for an activity or user's private custom activity using units in the unit system which corresponds to the Accept-Language header provided (or using optional custom distanceUnit) and get a response in the format requested.",
        "operationId": "addActivitiesLog",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/{activity-log-id}.json": {
      "delete": {
        "tags": ["Activity"],
        "summary": "Delete Activity Log",
        "description": "Deletes a user's activity log entry with the given ID.",
        "operationId": "deleteActivitiesLog",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/list.json": {
      "get": {
        "tags": ["Activity"],
        "summary": "Get Activity Log List",
        "description": "Retreives a list of user's activity log entries before or after a given day with offset and limit using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesLogList",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/{log-id}.tcx": {
      "get": {
        "tags": ["Activity"],
        "summary": "Get Activity TCX",
        "description": "Retreives the details of a user's location and heart rate data during a logged exercise activity.",
        "operationId": "getActivitiesTCX",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/activities.json": {
      "get": {
        "tags": ["Activity"],
        "summary": "Browse Activity Types",
        "description": "Retreives a tree of all valid Fitbit public activities from the activities catelog as well as private custom activities the user created in the format requested.",
        "operationId": "getActivitiesTypes",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/activities/{activity-id}.json": {
      "get": {
        "tags": ["Activity"],
        "summary": "Get Activity Type",
        "description": "Returns the detail of a specific activity in the Fitbit activities database in the format requested. If activity has levels, it also returns a list of activity level details.",
        "operationId": "getActivitiesTypeDetail",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/frequent.json": {
      "get": {
        "tags": ["Activity"],
        "summary": "Get Frequent Activities",
        "description": "Retreives a list of a user's frequent activities in the format requested using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFrequentActivities",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/recent.json": {
      "get": {
        "tags": ["Activity"],
        "summary": "Get Recent Activity Types",
        "description": "Retreives a list of a user's recent activities types logged with some details of the last activity log of that type using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getRecentActivities",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/favorite.json": {
      "get": {
        "tags": ["Activity"],
        "summary": "Get Favorite Activities",
        "description": "Returns a list of a user's favorite activities.",
        "operationId": "getFavoriteActivities",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/favorite/{activity-id}.json": {
      "post": {
        "tags": ["Activity"],
        "summary": "Add Favorite Activity",
        "description": "Adds the activity with the given ID to user's list of favorite activities.",
        "operationId": "addFavoriteActivities",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      },
      "delete": {
        "tags": ["Activity"],
        "summary": "Delete Favorite Activity",
        "description": "Removes the activity with the given ID from a user's list of favorite activities.",
        "operationId": "deleteFavoriteActivities",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/goals/{period}.json": {
      "get": {
        "tags": ["Activity"],
        "summary": "Get Activity Goals",
        "description": "Retreives a user's current daily or weekly activity goals using measurement units as defined in the unit system, which corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesGoals",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      },
      "post": {
        "tags": ["Activity"],
        "summary": "Update Activity Goals",
        "description": "Updates a user's daily or weekly activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "addUpdateActivitiesGoals",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/fat/date/{date}.json": {
      "get": {
        "tags": ["Body"],
        "summary": "Get Body Fat Logs",
        "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
        "operationId": "getBodyFatByDate",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/fat/date/{date}/{period}.json": {
      "get": {
        "tags": ["Body"],
        "summary": "Get Body Fat Logs",
        "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
        "operationId": "getBodyFatByDatePeriod",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/fat/date/{base-date}/{end-date}.json": {
      "get": {
        "tags": ["Body"],
        "summary": "Get Body Fat Logs",
        "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
        "operationId": "getBodyFatByDateRange",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/fat.json": {
      "post": {
        "tags": ["Body"],
        "summary": "Log Body Fat",
        "description": "Creates a log entry for body fat and returns a response in the format requested.",
        "operationId": "addBodyFatLog",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/fat/{body-fat-log-id}.json": {
      "delete": {
        "tags": ["Body"],
        "summary": "Delete Body Fat Log",
        "description": "Deletes a user's body fat log entry with the given ID.",
        "operationId": "deleteBodyFatLog",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/{goal-type}/goal.json": {
      "get": {
        "tags": ["Body"],
        "summary": "Get Body Goals",
        "description": "Retreives a user's current body fat percentage or weight goal using units in the unit systems that corresponds to the Accept-Language header providedin the format requested.",
        "operationId": "getBodyGoals",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/fat/goal.json": {
      "post": {
        "tags": ["Body"],
        "summary": "Update Body Fat Goal",
        "description": "Updates user's fat percentage goal.",
        "operationId": "UpdateBodyFatGoal",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/weight/goal.json": {
      "post": {
        "tags": ["Body"],
        "summary": "Update Weight Goal",
        "description": "Updates user's fat percentage goal.",
        "operationId": "updateWeightGoal",
        "security": [
          {
            "oauth2": ["profile", "heartrate", "location"]
          }
        ]
      }
    },
    "/1/user/-/body/log/weight/date/{date}.json": {
      "get": {
        "tags": ["Body"],
        "summary": "Get Weight Logs",
        "description": "Retreives a list of all user's body weight log entries for a given day using units in the unit systems which corresponds to the Accept-Language header provided.",
        "operationId": "getWeightByDate",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/weight/date/{date}/{period}.json": {
      "get": {
        "tags": ["Body"],
        "summary": "Get Body Fat Logs",
        "description": "Retreives a list of all user's body weight log entries for a given day in the format requested.",
        "operationId": "getWeightByDatePeriod",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/weight/date/{base-date}/{end-date}.json": {
      "get": {
        "tags": ["Body"],
        "summary": "Get Body Fat Logs",
        "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
        "operationId": "getWeightByDateRange",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/weight.json": {
      "post": {
        "tags": ["Body"],
        "summary": "Log Weight",
        "description": "Creates log entry for a body weight using units in the unit systems that corresponds to the Accept-Language header provided and gets a response in the format requested.",
        "operationId": "addWeightLog",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/log/weight/{body-weight-log-id}.json": {
      "delete": {
        "tags": ["Body"],
        "summary": "Delete Weight Log",
        "description": "Deletes a user's body weight log entrywith the given ID.",
        "operationId": "deleteWeightLog",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/{resource-path}/date/{date}/{period}.json": {
      "get": {
        "tags": ["Body Time Series"],
        "summary": "Get Body Time Series",
        "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getBodyResourceByDatePeriod",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/body/{resource-path}/date/{base-date}/{end-date}.json": {
      "get": {
        "tags": ["Body Time Series"],
        "summary": "Get Body Time Series",
        "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getBodyResourceByDateRange",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/br/date/{date}.json": {
      "get": {
        "tags": ["Breathing Rate"],
        "summary": "Get Breathing Rate Summary by Date",
        "description": "This endpoint returns average breathing rate data for a single date. Breathing Rate data applies specifically to a user’s “main sleep,” which is the longest single period of time during which they were asleep on a given date.",
        "operationId": "getBreathingRateSummaryByDate",
        "security": [
          {
            "oauth2": ["respiratory_rate"]
          }
        ]
      }
    },
    "/1/user/-/br/date/{startDate}/{endDate}.json": {
      "get": {
        "tags": ["Breathing Rate"],
        "summary": "Get Breathing Rate Summary by Interval",
        "description": "This endpoint returns average breathing rate data for a date range. Breathing Rate data applies specifically to a user’s “main sleep,” which is the longest single period of time during which they were asleep on a given date.",
        "operationId": "getBreathingRateSummaryByInterval",
        "security": [
          {
            "oauth2": ["respiratory_rate"]
          }
        ]
      }
    },
    "/1/user/-/br/date/{date}/all.json": {
      "get": {
        "tags": ["Breathing Rate Intraday"],
        "summary": "Get Breathing Rate Intraday by Date",
        "description": "This endpoint returns intraday breathing rate data for a single date. It measures the average breathing rate throughout the day and categories your breathing rate by sleep stage. Sleep stages vary between light sleep, deep sleep, REM sleep, and full sleep.",
        "operationId": "getBreathingRateIntradayByDate",
        "security": [
          {
            "oauth2": ["respiratory_rate"]
          }
        ]
      }
    },
    "/1/user/-/br/date/{startDate}/{endDate}/all.json": {
      "get": {
        "tags": ["Breathing Rate Intraday"],
        "summary": "Get Breathing Rate Intraday by Interval",
        "description": "This endpoint returns intraday breathing rate data for a date range. It measures the average breathing rate throughout the day and categories your breathing rate by sleep stage. Sleep stages vary between light sleep, deep sleep, REM sleep, and full sleep.",
        "operationId": "getBreathingRateIntradayByInterval",
        "security": [
          {
            "oauth2": ["respiratory_rate"]
          }
        ]
      }
    },
    "/1/user/-/cardioscore/date/{date}.json": {
      "get": {
        "tags": ["Cardio Fitness Score (VO2 Max)"],
        "summary": "Get VO2 Max Summary by Date",
        "description": "This endpoint returns the Cardio Fitness Score (VO2 Max) data for a single date. VO2 Max values will be shown as a range if no run data is available or a single numeric value if the user uses a GPS for runs.",
        "operationId": "getVo2MaxSummaryByDate",
        "security": [
          {
            "oauth2": ["cardio_fitness"]
          }
        ]
      }
    },
    "/1/user/-/cardioscore/date/{startDate}/{endDate}.json": {
      "get": {
        "tags": ["Cardio Fitness Score (VO2 Max)"],
        "summary": "Get VO2 Max Summary by Interval",
        "description": "This endpoint returns the Cardio Fitness Score (VO2 Max) data for a date range. VO2 Max values will be shown as a range if no run data is available or a single numeric value if the user uses a GPS for runs.",
        "operationId": "getVo2MaxSummaryByInterval",
        "security": [
          {
            "oauth2": ["cardio_fitness"]
          }
        ]
      }
    },
    "/1/user/-/devices.json": {
      "get": {
        "tags": ["Devices"],
        "summary": "Get Devices",
        "description": "Returns a list of the Fitbit devices connected to a user's account.",
        "operationId": "getDevices",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/devices/tracker/{tracker-id}/alarms.json": {
      "get": {
        "tags": ["Devices"],
        "summary": "Get Alarms",
        "description": "Returns alarms for a device",
        "operationId": "getAlarms",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      },
      "post": {
        "tags": ["Devices"],
        "summary": "Add Alarm",
        "description": "Adds the alarm settings to a given ID for a given device.",
        "operationId": "addAlarms",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/devices/tracker/{tracker-id}/alarms/{alarm-id}.json": {
      "post": {
        "tags": ["Devices"],
        "summary": "Update Alarm",
        "description": "Updates the alarm entry with a given ID for a given device. It also gets a response in the format requested.",
        "operationId": "updateAlarms",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      },
      "delete": {
        "tags": ["Devices"],
        "summary": "Delete Alarm",
        "description": "Deletes the user's device alarm entry with the given ID for a given device.",
        "operationId": "deleteAlarms",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/ecg/list.json": {
      "get": {
        "tags": ["Electrocardiogram"],
        "summary": "Get ECG Log List",
        "description": "This endpoint is used for querying the user's on-device ECG readings.",
        "operationId": "getEcgLogList",
        "security": [
          {
            "oauth2": ["electrocardiogram"]
          }
        ]
      }
    },
    "/1.1/user/-/friends.json": {
      "get": {
        "tags": ["Friends"],
        "summary": "Get Friends",
        "description": "Returns data of a user's friends in the format requested using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFriends",
        "security": [
          {
            "oauth2": ["social"]
          }
        ]
      }
    },
    "/1.1/user/-/leaderboard/friends.json": {
      "get": {
        "tags": ["Friends"],
        "summary": "Get Friends Leaderboard",
        "description": "Returns data of a user's friends in the format requested using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFriendsLeaderboard",
        "security": [
          {
            "oauth2": ["social"]
          }
        ]
      }
    },
    "/1/user/-/activities/heart/date/{date}/{period}.json": {
      "get": {
        "tags": ["Heart Rate Time Series"],
        "summary": "Get Heart Rate Time Series",
        "description": "Returns the time series data in the specified range for a given resource in the format requested using units in the unit systems that corresponds to the Accept-Language header provided.",
        "operationId": "getHeartByDatePeriod",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/heart/date/{base-date}/{end-date}.json": {
      "get": {
        "tags": ["Heart Rate Time Series"],
        "summary": "Get Heart Rate Time Series",
        "description": "Returns the time series data in the specified range for a given resource in the format requested using units in the unit systems that corresponds to the Accept-Language header provided.",
        "operationId": "getHeartByDateRange",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/heart/date/{date}/{end-date}/{detail-level}.json": {
      "get": {
        "tags": ["Heart Rate Intraday Time Series"],
        "summary": "Get Heart Rate Intraday Time Series",
        "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the authorized u[...]",
        "operationId": "getHeartByDateRangeIntraday",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/heart/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "tags": ["Heart Rate Intraday Time Series"],
        "summary": "Get Heart Rate Intraday Time Series",
        "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the authorized u[...]",
        "operationId": "getHeartByDateRangeTimestampIntraday",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/heart/date/{date}/1d/{detail-level}.json": {
      "get": {
        "tags": ["Heart Rate Intraday Time Series"],
        "summary": "Get Heart Rate Intraday Time Series",
        "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the authorized u[...]",
        "operationId": "getHeartByDateIntraday",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/activities/heart/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "tags": ["Heart Rate Intraday Time Series"],
        "summary": "Get Heart Rate Intraday Time Series",
        "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the authorized u[...]",
        "operationId": "getHeartByDateTimestampIntraday",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/hrv/date/{date}.json": {
      "get": {
        "tags": ["Heart Rate Variability"],
        "summary": "Get HRV Summary by Date",
        "description": "This endpoint returns the Heart Rate Variability (HRV) data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
        "operationId": "getHrvSummaryDate",
        "security": [
          {
            "oauth2": ["heartrate"]
          }
        ]
      }
    },
    "/1/user/-/hrv/date/{startDate}/{endDate}.json": {
      "get": {
        "tags": ["Heart Rate Variability"],
        "summary": "Get HRV Summary by Interval",
        "description": "This endpoint returns the Heart Rate Variability (HRV) data for a date range. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
        "operationId": "getHrvSummaryInterval",
        "security": [
          {
            "oauth2": ["heartrate"]
          }
        ]
      }
    },
    "/1/user/-/hrv/date/{date}/all.json": {
      "get": {
        "tags": ["Heart Rate Variability Intraday"],
        "summary": "Get HRV Intraday by Date",
        "description": "This endpoint returns the Heart Rate Variability (HRV) intraday data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
        "operationId": "getHrvIntradayByDate",
        "security": [
          {
            "oauth2": ["heartrate"]
          }
        ]
      }
    },
    "/1/user/-/hrv/date/{startDate}/{endDate}/all.json": {
      "get": {
        "tags": ["Heart Rate Variability Intraday"],
        "summary": "Get HRV Intraday by Interval",
        "description": "This endpoint returns the Heart Rate Variability (HRV) intraday data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
        "operationId": "getHrvIntradayByInterval",
        "security": [
          {
            "oauth2": ["heartrate"]
          }
        ]
      }
    },
    "/1/user/-/irn/alerts/list.json": {
      "get": {
        "tags": ["Irregular Rhythm Notifications"],
        "summary": "Get IRN Alerts List",
        "description": "This endpoint returns a paginated list of Irregular Rhythm Notifications (IRN) alerts, as well as all of the alert tachograms. This endpoint will only return alerts that the user has read in the Fitbit app already, as that is meant as the primary entrypoint for viewing notifications.",
        "operationId": "getIrnAlertsList",
        "security": [
          {
            "oauth2": ["irregular_rhythm_notifications"]
          }
        ]
      }
    },
    "/1/user/-/irn/profile.json": {
      "get": {
        "tags": ["Irregular Rhythm Notifications"],
        "summary": "Get IRN Profile",
        "description": "This endpoint returns the user state for Irregular Rhythm Notifications (IRN). The user state contains most information about the user’s current engagement with the feature, including onboarding progress and algorithm processing state.",
        "operationId": "getIrnProfile",
        "security": [
          {
            "oauth2": ["irregular_rhythm_notifications"]
          }
        ]
      }
    },
    "/1/foods/locales.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Food Locales",
        "description": "Returns the food locales that the user may choose to search, log, and create food in.",
        "operationId": "getFoodsLocales",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/goal.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Food Goals",
        "description": "Returns a user's current daily calorie consumption goal and/or foodPlan value in the format requested.",
        "operationId": "getFoodsGoal",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      },
      "post": {
        "tags": ["Nutrition"],
        "summary": "Update Food Goal",
        "description": "Updates a user's daily calories consumption goal or food plan and returns a response in the format requested.",
        "operationId": "addUpdateFoodsGoal",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/date/{date}.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Food Logs",
        "description": "Retreives a summary and list of a user's food log entries for a given day in the format requested.",
        "operationId": "getFoodsByDate",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/water/date/{date}.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Water Logs",
        "description": "Retreives a summary and list of a user's water log entries for a given day in the requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getWaterByDate",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/water/goal.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Water Goal",
        "description": "Retreives a summary and list of a user's water goal entries for a given day in the requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getWaterGoal",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      },
      "post": {
        "tags": ["Nutrition"],
        "summary": "Update Water Goal",
        "description": "Updates a user's daily calories consumption goal or food plan and returns a response in the format requested.",
        "operationId": "addUpdateWaterGoal",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/{resource-path}/date/{base-date}/{end-date}.json": {
      "get": {
        "tags": ["Nutrition Time Series"],
        "summary": "Get Food or Water Time Series",
        "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFoodsByDateRange",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/{resource-path}/date/{date}/{period}.json": {
      "get": {
        "tags": ["Nutrition Time Series"],
        "summary": "Get Food or Water Time Series",
        "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFoodsResourceByDatePeriod",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log.json": {
      "post": {
        "tags": ["Nutrition"],
        "summary": "Log Food",
        "description": "Creates food log entries for users with or without foodId value.",
        "operationId": "addFoodsLog",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/{food-log-id}.json": {
      "post": {
        "tags": ["Nutrition"],
        "summary": "Edit Food Log",
        "description": "The Edit Food Log endpoint changes the quantity or calories consumed for a user's food log entry with the given Food Log ID.",
        "operationId": "editFoodsLog",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      },
      "delete": {
        "tags": ["Nutrition"],
        "summary": "Delete Food Log",
        "description": "Deletes a user's food log entry with the given ID.",
        "operationId": "deleteFoodsLog",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/water.json": {
      "post": {
        "tags": ["Nutrition"],
        "summary": "Log Water",
        "description": "Creates a log entry for water using units in the unit systems that corresponds to the Accept-Language header provided.",
        "operationId": "addWaterLog",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/water/{water-log-id}.json": {
      "post": {
        "tags": ["Nutrition"],
        "summary": "Update Water Log",
        "description": "Updates a user's water log entry with the given ID.",
        "operationId": "updateWaterLog",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      },
      "delete": {
        "tags": ["Nutrition"],
        "summary": "Delete Water Log",
        "description": "Deletes a user's water log entry with the given ID.",
        "operationId": "deleteWaterLog",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/favorite.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Favorite Foods",
        "description": "Returns a list of a user's favorite foods in the format requested. A favorite food in the list provides a quick way to log the food via the Log Food endpoint.",
        "operationId": "getFavoriteFoods",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/frequent.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Frequent Foods",
        "description": "Returns a list of a user's frequent foods in the format requested. A frequent food in the list provides a quick way to log the food via the Log Food endpoint.",
        "operationId": "getFrequentFoods",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/favorite/{food-id}.json": {
      "post": {
        "tags": ["Nutrition"],
        "summary": "Add Favorite Food",
        "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "addFavoriteFood",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      },
      "delete": {
        "tags": ["Nutrition"],
        "summary": "Delete Favorite Food",
        "description": "Deletes a food with the given ID to the user's list of favorite foods.",
        "operationId": "deleteFavoriteFood",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/meals/{meal-id}.json": {
      "post": {
        "tags": ["Nutrition"],
        "summary": "Update Meal",
        "description": "Replaces an existing meal with the contents of the request. The response contains the updated meal.",
        "operationId": "updateMeal",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      },
      "delete": {
        "tags": ["Nutrition"],
        "summary": "Delete Meal",
        "description": "Deletes a user's meal with the given meal id.",
        "operationId": "deleteMeal",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/log/recent.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Recent Foods",
        "description": "Returns a list of a user's frequent foods in the format requested. A frequent food in the list provides a quick way to log the food via the Log Food endpoint.",
        "operationId": "getRecentFoods",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods.json": {
      "post": {
        "tags": ["Nutrition"],
        "summary": "Create Food",
        "description": "Creates a new private food for a user and returns a response in the format requested. The created food is found via the Search Foods call.",
        "operationId": "addFoods",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/user/-/foods/{food-id}.json": {
      "delete": {
        "tags": ["Nutrition"],
        "summary": "Delete Custom Food",
        "description": "Deletes custom food for a user and returns a response in the format requested.",
        "operationId": "deleteFoods",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/foods/{food-id}.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Food",
        "description": "Returns the details of a specific food in the Fitbit food databases or a private food that an authorized user has entered in the format requested.",
        "operationId": "getFoodsInfo",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/foods/units.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Get Food Units",
        "description": "Returns a list of all valid Fitbit food units in the format requested.",
        "operationId": "getFoodsUnits",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1/foods/search.json": {
      "get": {
        "tags": ["Nutrition"],
        "summary": "Search Foods",
        "description": "Returns a list of public foods from the Fitbit food database and private food the user created in the format requested.",
        "operationId": "getFoodsList",
        "security": [
          {
            "oauth2": ["nutrition"]
          }
        ]
      }
    },
    "/1.2/user/-/sleep/{log-id}.json": {
      "delete": {
        "tags": ["Sleep"],
        "summary": "Delete Sleep Log",
        "description": "Deletes a user's sleep log entry with the given ID.",
        "operationId": "deleteSleep",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1.2/user/-/sleep/date/{date}.json": {
      "get": {
        "tags": ["Sleep"],
        "summary": "Get Sleep Log",
        "description": "The Get Sleep Logs by Date endpoint returns a summary and list of a user's sleep log entries (including naps) as well as detailed sleep entry data for a given day.",
        "operationId": "getSleepByDate",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1.2/user/-/sleep/date/{base-date}/{end-date}.json": {
      "get": {
        "tags": ["Sleep"],
        "summary": "Get Sleep Logs by Date Range",
        "description": "The Get Sleep Logs by Date Range endpoint returns a list of a user's sleep log entries (including naps) as well as detailed sleep entry data for a given date range (inclusive of start and end dates).",
        "operationId": "getSleepByDateRange",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1.2/user/-/sleep/list.json": {
      "get": {
        "tags": ["Sleep"],
        "summary": "Get Sleep Logs List",
        "description": "The Get Sleep Logs List endpoint returns a list of a user's sleep logs (including naps) before or after a given day with offset, limit, and sort order.",
        "operationId": "getSleepList",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1.2/user/-/sleep/goal.json": {
      "get": {
        "tags": ["Sleep"],
        "summary": "Get Sleep Goal",
        "description": "Returns the user's sleep goal.",
        "operationId": "getSleepGoal",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      },
      "post": {
        "tags": ["Sleep"],
        "summary": "Update Sleep Goal",
        "description": "Create or update the user's sleep goal and get a response in the JSON format.",
        "operationId": "updateSleepGoal",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1.2/user/-/sleep.json": {
      "post": {
        "tags": ["Sleep"],
        "summary": "Log Sleep",
        "description": "Creates a log entry for a sleep event and returns a response in the format requested.",
        "operationId": "addSleep",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/spo2/date/{date}.json": {
      "get": {
        "tags": ["SpO2"],
        "summary": "Get SpO2 Summary by Date",
        "description": "This endpoint returns the SpO2 summary data for a single date. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getSpO2SummaryByDate",
        "security": [
          {
            "oauth2": ["oxygen_saturation"]
          }
        ]
      }
    },
    "/1/user/-/spo2/date/{startDate}/{endDate}.json": {
      "get": {
        "tags": ["SpO2"],
        "summary": "Get SpO2 Summary by Interval",
        "description": "This endpoint returns the SpO2 summary data for a date range. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getSpO2SummaryByInterval",
        "security": [
          {
            "oauth2": ["oxygen_saturation"]
          }
        ]
      }
    },
    "/1/user/-/spo2/date/{date}/all.json": {
      "get": {
        "tags": ["SpO2 Intraday"],
        "summary": "Get SpO2 Intraday by Date",
        "description": "This endpoint returns the SpO2 intraday data for a single date. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getSpO2IntradayByDate",
        "security": [
          {
            "oauth2": ["oxygen_saturation"]
          }
        ]
      }
    },
    "/1/user/-/spo2/date/{startDate}/{endDate}/all.json": {
      "get": {
        "tags": ["SpO2 Intraday"],
        "summary": "Get SpO2 Intraday by Interval",
        "description": "This endpoint returns the SpO2 intraday data for a specified date range. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getSpO2IntradayByInterval",
        "security": [
          {
            "oauth2": ["oxygen_saturation"]
          }
        ]
      }
    },
    "/1/user/-/{collection-path}/apiSubscriptions.json": {
      "get": {
        "tags": ["Subscriptions"],
        "summary": "Get a List of Subscriptions",
        "description": "Retreives a list of a user's subscriptions for your application in the format requested. You can either fetch subscriptions for a specific collection or the entire list of subscriptions for the user. For best practice, make sure that your application maintains this list on your side and use this endpoint only to periodically ensure data consistency.",
        "operationId": "getSubscriptionsList",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/{collection-path}/apiSubscriptions/{subscription-id}.json": {
      "post": {
        "tags": ["Subscriptions"],
        "summary": "Add a Subscription",
        "description": "Adds a subscription in your application so that users can get notifications and return a response in the format requested. The subscription-id value provides a way to associate an update with a particular user stream in your application.",
        "operationId": "addSubscriptions",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      },
      "delete": {
        "tags": ["Subscriptions"],
        "summary": "Delete a Subscription",
        "description": "Deletes a subscription for a user..",
        "operationId": "deleteSubscriptions",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/temp/core/date/{date}.json": {
      "get": {
        "tags": ["Temperature"],
        "summary": "Get Temperature (Core) Summary by Date",
        "description": "Returns the Temperature (Core) data for a single date. Temperature (Core) data applies specifically to data logged manually by the user throughout the day.",
        "operationId": "getTempCoreSummaryByDate",
        "security": [
          {
            "oauth2": ["temperature"]
          }
        ]
      }
    },
    "/1/user/-/temp/core/date/{startDate}/{endDate}.json": {
      "get": {
        "tags": ["Temperature"],
        "summary": "Get Temperature (Core) Summary by Interval",
        "description": "Returns Temperature (Core) data for a date range. Temperature (Core) data applies specifically to data logged manually by the user throughout the day and the maximum date range cannot exceed 30 days.",
        "operationId": "getTempCoreSummaryByInterval",
        "security": [
          {
            "oauth2": ["temperature"]
          }
        ]
      }
    },
    "/1/user/-/temp/skin/date/{date}.json": {
      "get": {
        "tags": ["Temperature"],
        "summary": "Get Temperature (Skin) Summary by Date",
        "description": "Returns the Temperature (Skin) data for a single date. Temperature (Skin) data applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getTempSkinSummaryDate",
        "security": [
          {
            "oauth2": ["temperature"]
          }
        ]
      }
    },
    "/1/user/-/temp/skin/date/{startDate}/{endDate}.json": {
      "get": {
        "tags": ["Temperature"],
        "summary": "Get Temperature (Skin) Summary by Interval",
        "description": "Returns Temperature (Skin) data for a date range. It only returns a value for dates on which the Fitbit device was able to record Temperature (skin) data and the maximum date range cannot exceed 30 days.",
        "operationId": "getTempSkinSummaryByInterval",
        "security": [
          {
            "oauth2": ["temperature"]
          }
        ]
      }
    },
    "/1/user/-/badges.json": {
      "get": {
        "tags": ["User"],
        "summary": "Get Badges",
        "description": "Retrieves the user's badges in the format requested. Response includes all badges for the user as seen on the Fitbit website badge locker (both activity and weight related.) The endpoint returns weight and distance badges based on the user's unit profile preference as on the website.",
        "operationId": "getBadges",
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ]
      }
    },
    "/1/user/-/profile.json": {
      "get": {
        "tags": ["User"],
        "summary": "Get Profile",
        "description": "Returns a user's profile. The authenticated owner receives all values. However, the authenticated user's access to other users' data is subject to those users' privacy settings. Numerical values are returned in the unit system specified in the Accept-Language header.",
        "operationId": "getProfile",
        "security": [
          {
            "oauth2": ["location", "profile", "weight"]
          }
        ]
      },
      "post": {
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://www.fitbit.com/oauth2/authorize",
            "scopes": {
              "activity": "Activity data and exercise log related features, such as steps, distance, calories burned, and active minutes",
              "cardio_fitness": "Maximum or optimum rate at which the user’s heart, lungs, and muscles can effectively use oxygen during exercise",
              "electrocardiogram": "A users on-device ECG readings",
              "heartrate": "Continuous heart rate & HRV data and related analysis",
              "irregular_rhythm_notifications": "Includes the users engagement and list of irregular rhythm notification alerts.",
              "location": "GPS and other location data",
              "nutrition": "Calorie consumption and nutrition related features, such as food/water logging, goals, and plans",
              "oxygen_saturation": "SpO2 (Oxygen Saturation) is a measurement of your blood oxygen level",
              "profile": "Basic user information",
              "respiratory_rate": "Respiratory Rate is a measurement of your breaths at night.",
              "settings": "User account and device settings, such as alarms",
              "sleep": "Sleep logs and related sleep analysis",
              "social": "Friend-related features, such as friend list and leaderboard",
              "temperature": "Core and skin temperature data",
              "weight": "Weight and related information, such as body mass index, body fat percentage, and goals"
            }
          }
        }
      }
    }
  },
  "x-original-swagger-version": "2.0"
}
