# coding: utf-8

# flake8: noqa

"""
    Fitbit Web API Explorer

    Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.  # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.active_zone_minutes_intraday_time_series_api import (
    ActiveZoneMinutesIntradayTimeSeriesApi,
)
from swagger_client.api.active_zone_minutes_time_series_api import (
    ActiveZoneMinutesTimeSeriesApi,
)
from swagger_client.api.activity_api import ActivityApi
from swagger_client.api.activity_intraday_time_series_api import (
    ActivityIntradayTimeSeriesApi,
)
from swagger_client.api.activity_time_series_api import ActivityTimeSeriesApi
from swagger_client.api.authorization_api import AuthorizationApi
from swagger_client.api.body_api import BodyApi
from swagger_client.api.body_time_series_api import BodyTimeSeriesApi
from swagger_client.api.breathing_rate_api import BreathingRateApi
from swagger_client.api.breathing_rate_intraday_api import BreathingRateIntradayApi
from swagger_client.api.cardio_fitness_score__vo2_max_api import (
    CardioFitnessScoreVO2MaxApi,
)
from swagger_client.api.devices_api import DevicesApi
from swagger_client.api.electrocardiogram_api import ElectrocardiogramApi
from swagger_client.api.friends_api import FriendsApi
from swagger_client.api.heart_rate_intraday_time_series_api import (
    HeartRateIntradayTimeSeriesApi,
)
from swagger_client.api.heart_rate_time_series_api import HeartRateTimeSeriesApi
from swagger_client.api.heart_rate_variability_api import HeartRateVariabilityApi
from swagger_client.api.heart_rate_variability_intraday_api import (
    HeartRateVariabilityIntradayApi,
)
from swagger_client.api.nutrition_api import NutritionApi
from swagger_client.api.nutrition_time_series_api import NutritionTimeSeriesApi
from swagger_client.api.sleep_api import SleepApi
from swagger_client.api.sp_o2_api import SpO2Api
from swagger_client.api.sp_o2_intraday_api import SpO2IntradayApi
from swagger_client.api.subscriptions_api import SubscriptionsApi
from swagger_client.api.temperature_api import TemperatureApi
from swagger_client.api.user_api import UserApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration

# import models into sdk package
from swagger_client.models.food_item import FoodItem
from swagger_client.models.meal import Meal
from swagger_client.models.oauth2_introspect_body import Oauth2IntrospectBody
from swagger_client.models.oauth2_revoke_body import Oauth2RevokeBody
from swagger_client.models.profile_json_body import ProfileJsonBody
