"""Fitbit Web API Explorer

Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field

from fitbit_web_api.models.sleep_log_levels_data_inner import SleepLogLevelsDataInner
from fitbit_web_api.models.sleep_log_levels_summary_value import (
    SleepLogLevelsSummaryValue,
)


class SleepLogLevels(BaseModel):
    """SleepLogLevels"""

    data: list[SleepLogLevelsDataInner] | None = None
    short_data: list[SleepLogLevelsDataInner] | None = Field(
        default=None,
        description="Short data periods (3 minutes or less) for stages sleep logs.",
        alias="shortData",
    )
    summary: dict[str, SleepLogLevelsSummaryValue] | None = None
    __properties: ClassVar[list[str]] = ["data", "shortData", "summary"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SleepLogLevels from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict["data"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in short_data (list)
        _items = []
        if self.short_data:
            for _item_short_data in self.short_data:
                if _item_short_data:
                    _items.append(_item_short_data.to_dict())
            _dict["shortData"] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in summary (dict)
        _field_dict = {}
        if self.summary:
            for _key_summary in self.summary:
                if self.summary[_key_summary]:
                    _field_dict[_key_summary] = self.summary[_key_summary].to_dict()
            _dict["summary"] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SleepLogLevels from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "data": (
                    [SleepLogLevelsDataInner.from_dict(_item) for _item in obj["data"]]
                    if obj.get("data") is not None
                    else None
                ),
                "shortData": (
                    [
                        SleepLogLevelsDataInner.from_dict(_item)
                        for _item in obj["shortData"]
                    ]
                    if obj.get("shortData") is not None
                    else None
                ),
                "summary": (
                    {
                        _k: SleepLogLevelsSummaryValue.from_dict(_v)
                        for _k, _v in obj["summary"].items()
                    }
                    if obj.get("summary") is not None
                    else None
                ),
            }
        )
        return _obj
